In [1]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

In [2]:
import os

print("current folder:", os.getcwd())
print("files in raw:")
for f in os.listdir("raw/"):
    print(" ", f)

current folder: c:\Users\hrikc\projects\arrears-analytics
files in raw:
  extract_20251222_01.csv
  extract_20251222_02.csv
  extract_20251222_03.csv
  real_sample_aemo_NEM12.csv

In [3]:
with open("raw/extract_20251222_01.csv") as f:
    lines = [line.strip() for line in f]

print(f"total lines: {len(lines)}")

from collections import Counter
record_types = [line.split(",")[0] for line in lines]
print(Counter(record_types))

total lines: 159
Counter({'300': 152, '200': 5, '100': 1, '900': 1})

In [4]:
import pandas as pd

def parse_nem12(filepath):
    rows =[]
    # state variables — the "current 200 context"
    current_nmi = None
    current_suffix = None
    current_meter = None
    current_interval = None


    with open(filepath) as f:
        for line in f:
           fields = line.strip().split(",")
           record_type = fields[0]

           if record_type == "200":
              current_nmi = fields[1]
              current_suffix = fields[4]
              current_meter = fields[6]
              current_interval = fields[8]

           elif record_type == "300":
                date = fields[1]
                # the interval values sit between the date and the quality flag
                # TODO: how many values? where do they end?
                # append one row per reading, OR one row per day for now — your call
                n_values = 48 if current_interval == "30" else 96
                values = fields[2:2+n_values]
                # TODO: Create DataFrame rows for each value
                for i, value in enumerate(values):
                    rows.append({
                        "nmi": current_nmi,
                        "suffix": current_suffix,
                        "meter": current_meter,
                        "date": date,
                        "interval": i+1,
                        "reading": value
                    })

    return pd.DataFrame(rows)

In [5]:
df = parse_nem12("raw/extract_20251222_01.csv")
print(df.shape)
df.head(10)

(7296, 6)

          nmi suffix     meter      date  interval reading
0  6305000001     E1  MET00001  20251101         1    0.04
1  6305000001     E1  MET00001  20251101         2    0.04
2  6305000001     E1  MET00001  20251101         3    0.04
3  6305000001     E1  MET00001  20251101         4    0.04
4  6305000001     E1  MET00001  20251101         5    0.04
5  6305000001     E1  MET00001  20251101         6    0.04
6  6305000001     E1  MET00001  20251101         7   0.041
7  6305000001     E1  MET00001  20251101         8   0.042
8  6305000001     E1  MET00001  20251101         9   0.046
9  6305000001     E1  MET00001  20251101        10   0.056

In [6]:
import glob

all_files = glob.glob("raw/*.csv")
print("files found:", all_files)

#parse each, collect into DataFrames
frames = [parse_nem12(f) for f in all_files]

#Stack them all together into one big DataFrame
df = pd.concat(frames, ignore_index=True)
print("combined shape:", df.shape)
df.head()

files found: ['raw\\extract_20251222_01.csv', 'raw\\extract_20251222_02.csv', 'raw\\extract_20251222_03.csv', 'raw\\real_sample_aemo_NEM12.csv']
combined shape: (20592, 6)

          nmi suffix     meter      date  interval reading
0  6305000001     E1  MET00001  20251101         1    0.04
1  6305000001     E1  MET00001  20251101         2    0.04
2  6305000001     E1  MET00001  20251101         3    0.04
3  6305000001     E1  MET00001  20251101         4    0.04
4  6305000001     E1  MET00001  20251101         5    0.04

In [7]:
df["nmi_length"] = df["nmi"].str.len()
print(df["nmi_length"].value_counts())
print("Total number of nmis to be fixed", (df["nmi_length"] != 10).sum())

nmi_length
10    19104
9      1488
Name: count, dtype: int64
Total number of nmis to be fixed 1488

In [8]:
df["reading_num"] = pd.to_numeric(df["reading"], errors="coerce")
print("negative readings:", (df["reading_num"] < 0).sum())

negative readings: 4

In [9]:
print("non-numeric readings:unparseable readings", df["reading_num"].isna().sum())

non-numeric readings:unparseable readings 34

In [10]:
dupes = df.duplicated(subset=["nmi", "suffix", "meter", "date", "interval"], keep=False).sum()
print("duplicate rows:", dupes)

duplicate rows: 672

In [11]:
dupes1 = df.duplicated(subset=["nmi", "suffix", "meter", "date", "interval"], keep=False).sum()
dupes2 = df.duplicated(subset=["nmi", "suffix", "meter", "date", "interval"]).sum()
print("duplicate rows:", dupes1)
print("duplicate rows:", dupes2)

duplicate rows: 672
duplicate rows: 336

In [12]:
clean = df.copy()
before = clean
after = clean.drop_duplicates(subset=["nmi", "suffix", "meter", "date", "interval"]).copy()
print(f"rows removed by dropping duplicates: {len(before) - len(after)}")
print(f"before -> {len(before)}, after -> {len(after)}")

rows removed by dropping duplicates: 336
before -> 20592, after -> 20256

In [13]:
clean = after.copy()
bad_nmis = clean[clean["nmi"].str.len() != 10].copy()
bad_nmis["exception_reason"] = "invalid nmi length"
clean = clean[clean["nmi"].str.len() == 10].copy()

print("quarantined invalid nmis:", len(bad_nmis))
print("remaining clean rows", len(clean))

quarantined invalid nmis: 1440
remaining clean rows 18816

In [14]:
print(clean["nmi"].str.len().value_counts())

nmi
10    18816
Name: count, dtype: int64

In [15]:
clean.dtypes

nmi                str
suffix             str
meter              str
date               str
interval         int64
reading            str
nmi_length       int64
reading_num    float64
dtype: object

In [16]:
bad_reads = clean[(clean["reading_num"].isna()) | (clean["reading_num"] < 0)].copy()
print("quarantined invalid readings:", len(bad_reads))
bad_reads["exception_reason"] = bad_reads["reading_num"].apply(lambda x: "negative reading" if x < 0 else "non-numeric reading")

quarantined invalid readings: 30

In [17]:
print(clean["reading_num"].isna().sum())
print(clean["nmi"].str.len().value_counts())

28
nmi
10    18816
Name: count, dtype: int64

In [18]:
print(len(bad_reads))
print(clean["nmi"].str.len().value_counts())

30
nmi
10    18816
Name: count, dtype: int64

In [19]:
print(clean["reading_num"].isna().sum())
clean = clean.dropna(subset=["reading_num"]).copy()
clean = clean[clean["reading_num"] >= 0].copy()
print("remaining clean rows after dropping invalid readings:", len(clean))

28
remaining clean rows after dropping invalid readings: 18786

In [20]:
print(len(bad_nmis))

1440

In [21]:
exceptions = pd.concat([bad_nmis, bad_reads], ignore_index=True)

In [22]:
print("total exceptions captured:", len(exceptions))
print(exceptions["exception_reason"].value_counts())

total exceptions captured: 1470
exception_reason
invalid nmi length     1440
non-numeric reading      28
negative reading          2
Name: count, dtype: int64

In [23]:
print(exceptions[exceptions["exception_reason"] == "negative_reading"].head())

Empty DataFrame
Columns: [nmi, suffix, meter, date, interval, reading, nmi_length, reading_num, exception_reason]
Index: []

In [24]:

# count how many intervals each meter recorded per day
interval_counts = (
    clean.groupby(["nmi", "suffix", "meter", "date"])
    .size()
    .reset_index(name="interval_count")
)

print(interval_counts["interval_count"].value_counts())

interval_count
48    204
96     81
47      5
95      4
93      3
94      2
45      2
46      1
Name: count, dtype: int64

In [25]:
interval_counts["is_complete"] = interval_counts["interval_count"].isin([48, 96])

In [26]:
incomplete_days = interval_counts[~interval_counts["is_complete"]].copy()
print(f"incomplete days: {len(incomplete_days)}")
print(incomplete_days.head())

incomplete days: 17
            nmi suffix     meter      date  interval_count  is_complete
170  6305000004     E1  MET00004  20251121              93        False
172  6305000004     E1  MET00004  20251123              93        False
176  6305000004     E1  MET00004  20251127              95        False
183  6305000005     E1  MET00005  20251104              95        False
187  6305000005     E1  MET00005  20251108              94        False

In [27]:
print(clean.shape)
print(clean["nmi"].str.len().value_counts())

(18786, 8)
nmi
10    18786
Name: count, dtype: int64

In [28]:
print(clean.head())

          nmi suffix     meter      date  interval reading  nmi_length  \
0  6305000001     E1  MET00001  20251101         1    0.04          10
1  6305000001     E1  MET00001  20251101         2    0.04          10
2  6305000001     E1  MET00001  20251101         3    0.04          10
3  6305000001     E1  MET00001  20251101         4    0.04          10
4  6305000001     E1  MET00001  20251101         5    0.04          10

   reading_num
0         0.04
1         0.04
2         0.04
3         0.04
4         0.04

In [29]:
#unique NMIs -> dimension table with surrogate key
dim_nmi = clean[["nmi"]].drop_duplicates().reset_index(drop=True)
dim_nmi["nmi_id"] = dim_nmi.index + 1  # surrogate key starting from 1

In [30]:
print(dim_nmi.head())

          nmi  nmi_id
0  6305000001       1
1  6305000002       2
2  6305000003       3
3  6305000004       4
4  6305000005       5

In [31]:
dim_meter = clean[["nmi", "suffix", "meter"]].drop_duplicates().reset_index(drop=True)
dim_meter["meter_id"] = dim_meter.index + 1  # surrogate key starting from 1

In [32]:
print(dim_meter)

           nmi suffix      meter  meter_id
0   6305000001     E1   MET00001         1
1   6305000001     B1   MET00001         2
2   6305000002     E1   MET00002         3
3   6305000003     E1   MET00003         4
4   6305000003     E2   MET00003         5
5   6305000004     E1   MET00004         6
6   6305000005     E1   MET00005         7
7   6305000006     E1   MET00006         8
8   6305000008     E1   MET00008         9
9   6305000009     E1   MET00009        10
10  VABD000163     E1  METSER123        11
11  VABD000163     Q1  METSER123        12

In [33]:
dim_meter = dim_meter.merge(dim_nmi, on="nmi", how="left")

In [34]:
print(dim_meter)

           nmi suffix      meter  meter_id  nmi_id
0   6305000001     E1   MET00001         1       1
1   6305000001     B1   MET00001         2       1
2   6305000002     E1   MET00002         3       2
3   6305000003     E1   MET00003         4       3
4   6305000003     E2   MET00003         5       3
5   6305000004     E1   MET00004         6       4
6   6305000005     E1   MET00005         7       5
7   6305000006     E1   MET00006         8       6
8   6305000008     E1   MET00008         9       7
9   6305000009     E1   MET00009        10       8
10  VABD000163     E1  METSER123        11       9
11  VABD000163     Q1  METSER123        12       9

In [35]:
print("NMIs length in clean table:", clean["nmi"].str.len().value_counts())

NMIs length in clean table: nmi
10    18786
Name: count, dtype: int64

In [36]:
fact_reading = clean.merge(dim_meter, on=["nmi", "suffix", "meter"], how="left")

In [37]:
print(fact_reading.head())

          nmi suffix     meter      date  interval reading  nmi_length  \
0  6305000001     E1  MET00001  20251101         1    0.04          10
1  6305000001     E1  MET00001  20251101         2    0.04          10
2  6305000001     E1  MET00001  20251101         3    0.04          10
3  6305000001     E1  MET00001  20251101         4    0.04          10
4  6305000001     E1  MET00001  20251101         5    0.04          10

   reading_num  meter_id  nmi_id
0         0.04         1       1
1         0.04         1       1
2         0.04         1       1
3         0.04         1       1
4         0.04         1       1

In [38]:
fact_reading=fact_reading[["meter_id", "date", "interval", "reading_num"]].copy()

In [40]:
print(fact_reading.head())
print(fact_reading.shape)

   meter_id      date  interval  reading_num
0         1  20251101         1         0.04
1         1  20251101         2         0.04
2         1  20251101         3         0.04
3         1  20251101         4         0.04
4         1  20251101         5         0.04
(18786, 4)